# This file contains default values, and does not need to be edited. All
# important settings can be changed from the admin interface.

defaults: &defaults
  site_title: Vegeterians.live
  site_short_description: ''
  site_description: ''
  site_extended_description: ''
  site_terms: ''
  site_contact_username: ''
  site_contact_email: ''
  registrations_mode: 'open'
  profile_directory: true
  closed_registrations_message: ''
  open_deletion: true
  min_invite_role: 'admin'
  timeline_preview: true
  show_staff_badge: true
  default_sensitive: false
  hide_network: false
  unfollow_modal: false
  boost_modal: false
  delete_modal: true
  auto_play_gif: false
  display_media: 'default'
  expand_spoilers: false
  preview_sensitive_media: false
  reduce_motion: false
  show_application: true
  group_in_home_feed: true
  noindex: false
  theme: 'default'
  aggregate_reblogs: true
  notification_emails:
    follow: false
    reblog: false
    favourite: false
    mention: false
    follow_request: true
    digest: true
    report: true
    pending_account: true
    emails_from_gabcom: true
  interactions:
    must_be_follower: false
    must_be_following: false
    must_be_following_dm: false
  reserved_usernames:
    - about
    - account
    - accounts
    - admin
    - administrator
    - api
    - blocks
    - compose
    - filters
    - group
    - groups
    - help
    - home
    - inbox
    - intent
    - interact
    - invites
    - list
    - lists
    - manifest
    - media
    - mod
    - moderator
    - mutes
    - notifications
    - public
    - root
    - search
    - settings
    - share
    - src
    - support
    - tag
    - tags
    - timeline
    - user
    - username
    - users
    - webmaster
    - welcome
    - bookmarks
  disallowed_hashtags: # space separated string or list of hashtags without the hash
  bootstrap_timeline_accounts: ''
  activity_api_enabled: true
  peers_api_enabled: true
  show_known_fediverse_at_about_page: true

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
