---
:concurrency: 5
:queues:
  - [default, 6]
  - [push, 4]
  - [mailers, 2]
  - [pull]
:schedule:
  scheduled_statuses_scheduler:
    every: '1m'
    class: Scheduler::ScheduledStatusesScheduler
  subscriptions_scheduler:
    cron: '<%= Random.rand(0..59) %> <%= Random.rand(4..6) %> * * *'
    class: Scheduler::SubscriptionsScheduler
  media_cleanup_scheduler:
    cron: '<%= Random.rand(0..59) %> <%= Random.rand(3..5) %> * * *'
    class: Scheduler::MediaCleanupScheduler
  feed_cleanup_scheduler:
    cron: '<%= Random.rand(0..59) %> <%= Random.rand(0..2) %> * * *'
    class: Scheduler::FeedCleanupScheduler
  doorkeeper_cleanup_scheduler:
    cron: '<%= Random.rand(0..59) %> <%= Random.rand(0..2) %> * * 0'
    class: Scheduler::DoorkeeperCleanupScheduler
  user_cleanup_scheduler:
    cron: '<%= Random.rand(0..59) %> <%= Random.rand(4..6) %> * * *'
    class: Scheduler::UserCleanupScheduler
  subscriptions_cleanup_scheduler:
    cron: '<%= Random.rand(0..59) %> <%= Random.rand(1..3) %> * * 0'
    class: Scheduler::SubscriptionsCleanupScheduler
  ip_cleanup_scheduler:
    cron: '<%= Random.rand(0..59) %> <%= Random.rand(3..5) %> * * *'
    class: Scheduler::IpCleanupScheduler
  email_scheduler:
    cron: '0 10 * * 2'
    class: Scheduler::EmailScheduler
  backup_cleanup_scheduler:
    cron: '<%= Random.rand(0..59) %> <%= Random.rand(3..5) %> * * *'
    class: Scheduler::BackupCleanupScheduler
  pghero_scheduler:
    cron: '0 0 * * *'
    class: Scheduler::PgheroScheduler
